resources:
  - name: S_PS_Generic_0066_GitRepo
    type: GitRepo
    configuration:
      path: rahulnlb1/powershel-ooo
      gitProvider: rahulgithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: pipelines_PS_Generic_0066
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - "10.18.0"
    steps:
       - name: S_PS_Generic_0066
         type: PowerShell
         configuration:
           nodePool: win_2019
           inputResources:
              - name: S_PS_Generic_0066_GitRepo
         execution:
           onExecute:
             - Push-Location $res_S_PS_Generic_0066_GitRepo_resourcePath/tests/core/oom
             - fsutil file createnew output.dat 104857600 #100MB
             - Get-ChildItem
             - node oom.js
             - Pop-Location
